#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import sys
sys.path.append('/usr/lib64/mirrors')
from mc_param import McParam
from mc_daemon import McDaemon

param = McParam()
obj = McDaemon(param)
obj.run()
sys.exit(0)
